Change call to macro require_all() to support elixir 1.20
When trying to compile the library with elixir 1.20.0-rc.1  I get the following error:

== Compilation error in file lib/gen_mcp.ex ==
** (UndefinedFunctionError) function GenMCP.MCP.ModMap.require_all/0 is undefined or private. However, there is a macro with the same name and arity. Be sure to require GenMCP.MCP.ModMap if you intend to invoke this macro
    GenMCP.MCP.ModMap.require_all()
    lib/gen_mcp.ex:65: (module)
could not compile dependency :gen_mcp, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile gen_mcp --force", update it with "mix deps.update gen_mcp" or clean it with "mix deps.clean gen_mcp"

This is probably due to the new compiler checks